### ISSUE TITLE
Not visible on iOS.

### ISSUE THREAD

**Issue by aptonline** [hacs/frontend#34] opened 2019-11-27 11:11 UTC
Hi, prior to 0.17.x I could use HACS in both the Home Assistant app and Safari on iOS but now all I get it a blank white screen. It works ok in safari on desktop, but again sometimes this required a refresh of the page to work. A refresh on iOS doesn’t work.

I’m currently using 0.17.4.

**Comment by ludeeus** [comment] 2019-11-27 12:04
Make sure you are using the latest iOS version

**Comment by aptonline** [comment] 2019-11-27 15:29
Running iOS 13.2.3, also used the previous Home Assistant app and the recent 2.0 release and same issue.

**Comment by aptonline** [comment] 2019-11-27 15:33
It may be the same issue as this:
https://github.com/hacs/frontend/issues/26

**Comment by ludeeus** [comment] 2019-11-27 15:36
In that case I can probably not fix it

**Comment by aptonline** [comment] 2019-11-27 15:57
Mmm this worked prior to 0.17.x though. What’s changed?

**Comment by ludeeus** [comment] 2019-11-27 15:58
Everything, the frontend was rebuild

**Comment by aptonline** [comment] 2019-11-27 18:51
Which in turn broke it for iOS users? And you don’t feel that this needs to be fixed?

**Comment by ludeeus** [comment] 2019-11-27 19:06
I'm not saying it does not need to be fixed, I'm saying I can't do it.
As I said in #26 without being able to reproduce it, I can't do anything.

**Comment by ludeeus** [comment] 2019-11-27 19:08
Borrowed an iOS device, and it works there so your issue is probably the same as #26 
Closing this as I have confirmed that iOS works as intended.

**Closed** 2019-11-27 19:08 UTC
