### ISSUE TITLE
History back reloads page

### ISSUE THREAD

**Issue by quthla** [hacs/frontend#66] opened 2020-01-13 09:36 UTC
Reproduce:

- Open HACS tab in sidebar
- Use browser controls to go back in history
=> Site reloads, will not go back

This only happens after browsing through the HACS tab

HACS version: 0.20.7

**Comment by ludeeus** [comment] 2020-02-09 10:39
Duplicate of #72

**Closed by ludeeus** 2020-02-09 10:39 UTC
